# Generated by Django 5.2.1 on 2025-06-11 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="marca",
        ),
    ]
