# Generated by Django 5.2.1 on 2025-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_remove_producto_marca"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="rut",
        ),
        migrations.AddField(
            model_name="profile",
            name="dni",
            field=models.CharField(
                blank=True, max_length=8, null=True, unique=True, verbose_name="DNI"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio en soles (S/). Usa punto como separador decimal.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="acepta_terminos",
            field=models.BooleanField(
                default=False, verbose_name="Acepta términos y condiciones"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="direccion",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telefono",
            field=models.CharField(max_length=15, unique=True, verbose_name="Teléfono"),
        ),
    ]
