# Generated by Django 5.2.1 on 2025-06-12 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_remove_profile_rut_profile_dni_alter_producto_precio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pago",
            name="user",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="pago",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="user",
        ),
        migrations.DeleteModel(
            name="LineaVenta",
        ),
        migrations.DeleteModel(
            name="Pago",
        ),
        migrations.DeleteModel(
            name="Venta",
        ),
    ]
